# docker compose -f docker-compose.dev.yml up
# docker compose -f docker-compose.dev.yml up --build -d
# docker-compose -f docker-compose.dev.yml down -v
# docker exec -it <container-name> bash

services:
  mysql:
    image: mysql
    container_name: mysql_local
    ports:
      - '3310:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: 100

volumes:
  mysql_data:

networks:
  mysql_network:
